# Generated by Django 5.2.11 on 2026-02-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('TO_UNI', 'Going to University'), ('FROM_UNI', 'Coming from University'), ('LUNCH', 'Lunch'), ('OTHER', 'Other')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
